version: "3.8"

services:
  postgres:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    # volumes:
    #   - ./var/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - route-roam-network
  minio1:
    image: minio/minio
    volumes:
      - ./docker-volume/minio:/data
    ports:
      - 9000:9000
    expose:
      - 9000
    environment:
      MINIO_ACCESS_KEY: route-roam
      MINIO_SECRET_KEY: route-roam
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - route-roam-network
  redis:
    image: redis:6.0.6
    # volumes: 
    #   - ./docker-volume/:/data
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: always
    networks:
      - route-roam-network
  go-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 8080
    depends_on:
      - redis
      - postgres
      - minio1
    volumes: 
      - .:/app
    networks:
      - route-roam-network
  nextjs:
    ports:
      - 3000:3000
      - 80:80
    expose:
      - 3000
    build:
      context: ./route-roam-web
      dockerfile: Dockerfile
    depends_on:
      - go-service
    networks:
      - route-roam-network
networks:
  route-roam-network:
    name: route-roam-network


