version: "3.8"

services:
   postgres:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    # volumes:
    #   - ./var/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    networks:
      - route-roam-network

networks:
  route-roam-network:
    name: route-roam-network


